version: '3.1'

services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile.postgres
    container_name: devtraining-db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - .pgdata:/var/lib/posgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

